name: Java CI with Maven

on:
  push:
    branches: [ master ]

# TODO: JAR SIGINING REQUIRES A GPG KEY, NEED TO ADD TO GITHUB SECRETS

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}  # TODO:
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}  # TODO:
      - name: Verify
        run: mvn --batch-mode --update-snapshots verify

